### ISSUE TITLE
Error farming bitcoin

### ISSUE THREAD

**Issue by aleexnl** [jordann7778/esx_bitcoinv2#3]
When I try to farm bitcoin it drops this error:
_SCRIPT ERROR: @esx_bitcoinv2/server/main.lua:34: attempt to compare nil with number_
We can't also import the SQL because it does not use esx new format.

**Comment by aleexnl** [comment]
I managed to start farming bitcoin. The problem is from the condition comparing the limit.

**Comment by morais5** [comment]
I will analyze,
Thank you for letting me know.

**Comment by morais5** [comment]
and what is the new esx?

**Comment by TheXtreamYT01** [comment]
Hi I have the same issue what do I need to change to fix this?

Best Regards

**Comment by TheXtreamYT01** [comment]
@jordann7778  have you fixed this issue?

**Comment by TheXtreamYT01** [comment]
@aleexnl Can you tell me how to fix this?

**Comment by aleexnl** [comment]
Substitude line 26 function with this
```
--Bitcoin Farm
local function HarvestKoda(source)
	SetTimeout(Config.TimeToFarm, function()
		if PlayersHarvestingKoda[source] then
			local xPlayer = ESX.GetPlayerFromId(source)

			if xPlayer.canCarryItem('bitcoinitem', 1) then
				xPlayer.addInventoryItem('bitcoinitem', 1)
				HarvestKoda(source)
			else
				TriggerClientEvent('esx:showNotification', source, _U('inventory_full'))
			end
		end
	end)
end
```

**Comment by TheXtreamYT01** [comment]
@aleexnl Ok now the error is gone but I cant start farming it says my inv is full

**Comment by TheXtreamYT01** [comment]
@aleexnl ty sooo much I got it working now

**Comment by morais5** [comment]
Hey the script is out of date for the new ESX
